/*
Primarias
Definición de claves primarias
*/

ALTER TABLE MUNDOS                  ADD CONSTRAINT PK_MUNDOS         PRIMARY KEY (nombreMundo);
ALTER TABLE CONTINENTES             ADD CONSTRAINT PK_CONTINENTES    PRIMARY KEY (nombreContinente, nombreMundo);
ALTER TABLE PAISES                  ADD CONSTRAINT PK_PAISES         PRIMARY KEY (nombrePais, nombreContinente, nombreMundo);
ALTER TABLE CIUDADES                ADD CONSTRAINT PK_CIUDADES       PRIMARY KEY (nombreCiudad, nombrePais, nombreContinente, nombreMundo);
ALTER TABLE RAZAS                   ADD CONSTRAINT PK_RAZAS          PRIMARY KEY (nombreR);
ALTER TABLE CLASES                  ADD CONSTRAINT PK_CLASES         PRIMARY KEY (nombreC);
ALTER TABLE COMBINACIONES           ADD CONSTRAINT PK_COMBINACIONES  PRIMARY KEY (raza, clase);
ALTER TABLE BONIFICACIONESRACIALES  ADD CONSTRAINT PK_BONIF          PRIMARY KEY (raza);
ALTER TABLE LOGROS                  ADD CONSTRAINT PK_LOGROS         PRIMARY KEY (nombreLogro);
ALTER TABLE PROFESIONES             ADD CONSTRAINT PK_PROFESIONES    PRIMARY KEY (nombreProfesion);
ALTER TABLE ICONOS                  ADD CONSTRAINT PK_ICONOS         PRIMARY KEY (idIcono);
ALTER TABLE HECHIZOS                ADD CONSTRAINT PK_HECHIZOS       PRIMARY KEY (idHechizo);
ALTER TABLE MACROS                  ADD CONSTRAINT PK_MACROS         PRIMARY KEY (idMacro);
ALTER TABLE MONTURAS                ADD CONSTRAINT PK_MONTURAS       PRIMARY KEY (nombreMontura);
ALTER TABLE MASCOTAS                ADD CONSTRAINT PK_MASCOTAS       PRIMARY KEY (nombreMascota);
ALTER TABLE JUGUETES                ADD CONSTRAINT PK_JUGUETES       PRIMARY KEY (nombreJuguete);
ALTER TABLE ARMAS                   ADD CONSTRAINT PK_ARMAS          PRIMARY KEY (nombreArma);
ALTER TABLE ROPAS                   ADD CONSTRAINT PK_ROPAS          PRIMARY KEY (nombreRopa);
ALTER TABLE TRASFIGURACIONES        ADD CONSTRAINT PK_TRASFIG        PRIMARY KEY (idTrasfiguracion);
ALTER TABLE NPCS                    ADD CONSTRAINT PK_NPCS           PRIMARY KEY (nombre);
ALTER TABLE MISIONES                ADD CONSTRAINT PK_MISIONES       PRIMARY KEY (idMision);
ALTER TABLE OBJETOS                 ADD CONSTRAINT PK_OBJETOS        PRIMARY KEY (idObjeto);
ALTER TABLE RECOMPENSAS             ADD CONSTRAINT PK_RECOMPENSAS    PRIMARY KEY (idMision, idObjeto);
ALTER TABLE MOBS                    ADD CONSTRAINT PK_MOBS           PRIMARY KEY (idMob);
ALTER TABLE PVBS                    ADD CONSTRAINT PK_PVBS           PRIMARY KEY (idPvB);
ALTER TABLE HERMANDADES             ADD CONSTRAINT PK_HERMANDADES    PRIMARY KEY (idHermandad);
ALTER TABLE PERSONAJES              ADD CONSTRAINT PK_PERSONAJES     PRIMARY KEY (idPersonaje);
ALTER TABLE PJ_ESTADISTICAS         ADD CONSTRAINT PK_PJ_ESTADIST    PRIMARY KEY (nombrePJ);
ALTER TABLE PJ_MONTURAS             ADD CONSTRAINT PK_PJ_MONTURAS    PRIMARY KEY (nombrePJ, nombreMontura);
ALTER TABLE PJ_MASCOTAS             ADD CONSTRAINT PK_PJ_MASCOTAS    PRIMARY KEY (nombrePJ, nombreMascota);
ALTER TABLE PJ_JUGUETES             ADD CONSTRAINT PK_PJ_JUGUETES    PRIMARY KEY (nombrePJ, nombreJuguete);
ALTER TABLE PJ_ARMAS                ADD CONSTRAINT PK_PJ_ARMAS       PRIMARY KEY (nombrePJ, nombreArma);
ALTER TABLE PJ_ROPAS                ADD CONSTRAINT PK_PJ_ROPAS       PRIMARY KEY (nombrePJ, nombreRopa);
ALTER TABLE PJ_MOBS                 ADD CONSTRAINT PK_PJ_MOBS        PRIMARY KEY (nombrePJ, mob);
ALTER TABLE PJ_BOSSES               ADD CONSTRAINT PK_PJ_BOSSES      PRIMARY KEY (nombrePJ, mob);
ALTER TABLE PJ_MISIONES             ADD CONSTRAINT PK_PJ_MISIONES    PRIMARY KEY (nombrePJ, mision);
ALTER TABLE PJ_VENTAS               ADD CONSTRAINT PK_PJ_VENTAS      PRIMARY KEY (nombrePJ, objeto);
ALTER TABLE PJ_COMPRAS              ADD CONSTRAINT PK_PJ_COMPRAS     PRIMARY KEY (nombrePJ, objeto);
ALTER TABLE ESPECIALIZACIONES       ADD CONSTRAINT PK_ESPEC          PRIMARY KEY (idPersonaje, idHechizo);
ALTER TABLE RANKINGPERSONAJES       ADD CONSTRAINT PK_RANKPJ         PRIMARY KEY (posicion);
ALTER TABLE RANKINGHERMANDADES      ADD CONSTRAINT PK_RANKHERM       PRIMARY KEY (posicion);