/*
Atributos
Definición de restricciones para un único atributos (TIpos)
*/

-- CONTINENTES: clima
ALTER TABLE CONTINENTES ADD CONSTRAINT CHK_CONT_CLIMA CHECK (clima IN ('FRIO','TEMPLADO','CALIDO','TROPICAL'));

-- CONTINENTES: nivelRecomendado
ALTER TABLE CONTINENTES ADD CONSTRAINT CHK_CONT_NIVEL CHECK (nivelRecomendado BETWEEN 1 AND 90);

-- PAISES: tipoZona
ALTER TABLE PAISES ADD CONSTRAINT CHK_PAIS_ZONA CHECK (tipoZona IN ('BOSQUE','DESIERTO','MONTANA','PANTANO','SAVANA','NEVADO'));

-- PAISES: nivelRecomendado
ALTER TABLE PAISES ADD CONSTRAINT CHK_PAIS_NIVEL CHECK (nivelRecomendado BETWEEN 1 AND 90);

-- CIUDADES: nivelRecomendado
ALTER TABLE CIUDADES ADD CONSTRAINT CHK_CIU_NIVEL CHECK (nivelRecomendado BETWEEN 1 AND 90);

-- CIUDADES: faccionDominante
ALTER TABLE CIUDADES ADD CONSTRAINT CHK_CIU_FACCION CHECK (faccionDominante IN ('ALIANZA','HORDA','NEUTRA'));

-- RAZAS: faccion
ALTER TABLE RAZAS ADD CONSTRAINT CHK_RAZA_FACCION CHECK (faccion IN ('ALIANZA','HORDA','NEUTRA'));

-- CLASES: rolPrincipal
ALTER TABLE CLASES ADD CONSTRAINT CHK_CLASE_ROL CHECK (rolPrincipal IN ('TANQUE','HEALER','DPS'));

-- COMBINACIONES: valido es 0 o 1
ALTER TABLE COMBINACIONES ADD CONSTRAINT CHK_COMB_VALIDO CHECK (valido IN (0,1));

-- MONTURAS: esVoladora es 0 o 1
ALTER TABLE MONTURAS ADD CONSTRAINT CHK_MONT_VOLA CHECK (esVoladora IN (0,1));

-- MONTURAS: nivelRequerido
ALTER TABLE MONTURAS ADD CONSTRAINT CHK_MONT_NIVEL CHECK (nivelRequerido BETWEEN 1 AND 90);

-- MASCOTAS: esCombate es 0 o 1
ALTER TABLE MASCOTAS ADD CONSTRAINT CHK_MASC_COMBATE CHECK (esCombate IN (0,1));

-- MASCOTAS: nivelMascota
ALTER TABLE MASCOTAS ADD CONSTRAINT CHK_MASC_NIVEL CHECK (nivelMascota BETWEEN 1 AND 25);

-- JUGUETES: esAplicable es 0 o 1
ALTER TABLE JUGUETES ADD CONSTRAINT CHK_JUG_APLIC CHECK (esAplicable IN (0,1));

-- ARMAS: esDosManos es 0 o 1
ALTER TABLE ARMAS ADD CONSTRAINT CHK_ARMA_DOSMANOS CHECK (esDosManos IN (0,1));

-- ARMAS: nivelRequerido
ALTER TABLE ARMAS ADD CONSTRAINT CHK_ARMA_NIVEL CHECK (nivelRequerido BETWEEN 1 AND 90);

-- ROPAS: daEstadisticas es 0 o 1
ALTER TABLE ROPAS ADD CONSTRAINT CHK_ROPA_DASTAT CHECK (daEstadisticas IN (0,1));

-- NPCS: tipo
ALTER TABLE NPCS ADD CONSTRAINT CHK_NPC_TIPO CHECK (tipo IN ('VENDEDOR','QUEST_GIVER','ENTRENADOR','VUELO'));

-- MISIONES: nivelRequerido
ALTER TABLE MISIONES ADD CONSTRAINT CHK_MIS_NIVEL CHECK (nivelRequerido BETWEEN 1 AND 90);

-- MISIONES: tipoMision
ALTER TABLE MISIONES ADD CONSTRAINT CHK_MIS_TIPO CHECK (tipoMision IN ('HISTORIA','SECUNDARIA','DIARIA'));

-- MOBS: nivel
ALTER TABLE MOBS ADD CONSTRAINT CHK_MOB_NIVEL CHECK (nivel BETWEEN 1 AND 90);

-- MOBS: tipoCriatura
ALTER TABLE MOBS ADD CONSTRAINT CHK_MOB_TIPO CHECK (tipoCriatura IN ('DRAGON','NO MUERTO','DEMONIO','ELEMENTAL','BESTIA',
'HUMANOIDE','GIGANTE','ABERRACION','MECANICO','CRIATURA MAGICA','TITAN','ANCESTRAL','ESPIRITU','GUARDIAN','SENOR DEL VACIO'));

-- MOBS: comportamiento
ALTER TABLE MOBS ADD CONSTRAINT CHK_MOB_COMP CHECK (comportamiento IN ('PASIVO','AGRESIVO','DEFENSIVO'));

-- PVBS: resultado
ALTER TABLE PVBS ADD CONSTRAINT CHK_PVB_RESULTADO CHECK (resultado IN ('VICTORIA','DERROTA','EMPATE'));

-- PVBS: dificultad
ALTER TABLE PVBS ADD CONSTRAINT CHK_PVB_DIFIC CHECK (dificultad IN ('NORMAL','HEROICO','MITICO'));

-- PVBS: duracion no negativa
ALTER TABLE PVBS ADD CONSTRAINT CHK_PVB_DUR CHECK (duracion >= 1);

-- PVBS: damageTotal y sanacionTotal no negativos
ALTER TABLE PVBS ADD CONSTRAINT CHK_PVB_DMG CHECK (damageTotal >= 0);
ALTER TABLE PVBS ADD CONSTRAINT CHK_PVB_SAN CHECK (sanacionTotal >= 0);

-- PERSONAJES: nivel
ALTER TABLE PERSONAJES ADD CONSTRAINT CHK_PJ_NIVEL CHECK (nivel BETWEEN 1 AND 90);

-- PERSONAJES: experiencia no negativa
ALTER TABLE PERSONAJES ADD CONSTRAINT CHK_PJ_EXP CHECK (experiencia >= 0);

-- PERSONAJES: salud no negativa
ALTER TABLE PERSONAJES ADD CONSTRAINT CHK_PJ_SALUD CHECK (salud >= 0);

-- PERSONAJES: oro no negativo
ALTER TABLE PERSONAJES ADD CONSTRAINT CHK_PJ_ORO CHECK (oro >= 0);

-- PERSONAJES: estado
ALTER TABLE PERSONAJES ADD CONSTRAINT CHK_PJ_ESTADO CHECK (estado IN ('VIVO','MUERTO','EN COMBATE'));

-- PJ_VENTAS: vendido es 0 o 1
ALTER TABLE PJ_VENTAS ADD CONSTRAINT CHK_VEN_VENDIDO CHECK (vendido IN (0,1));

-- ICONOS: formato
ALTER TABLE ICONOS ADD CONSTRAINT CHK_ICON_FORMATO CHECK (formato IN ('PNG','JPG'));

-- HERMANDADES: nivelHermandades
ALTER TABLE HERMANDADES ADD CONSTRAINT CHK_HERM_NIVEL CHECK (nivelHermandades BETWEEN 1 AND 30);

-- OBJETOS: Los tipos son 'Montura','Mascota','Juguete','Arma','Ropa'
ALTER TABLE OBJETOS ADD CONSTRAINT CHK_OBJ_TIPO CHECK (tipoObjeto IN ('Montura','Mascota','Juguete','Arma','Ropa'));