/*
Foraneas
Definición de claves foraneas
*/

-- CONTINENTES -> MUNDOS
ALTER TABLE CONTINENTES ADD CONSTRAINT FK_CONT_MUNDO FOREIGN KEY (nombreMundo) REFERENCES MUNDOS(nombreMundo);

-- PAISES -> CONTINENTES
ALTER TABLE PAISES ADD CONSTRAINT FK_PAIS_CONT FOREIGN KEY (nombreContinente, nombreMundo) REFERENCES CONTINENTES(nombreContinente, nombreMundo);

-- CIUDADES -> PAISES
ALTER TABLE CIUDADES ADD CONSTRAINT FK_CIU_PAIS FOREIGN KEY (nombrePais, nombreContinente, nombreMundo)
REFERENCES PAISES(nombrePais, nombreContinente, nombreMundo);

-- BONIFICACIONESRACIALES -> RAZAS
ALTER TABLE BONIFICACIONESRACIALES ADD CONSTRAINT FK_BONIF_RAZA FOREIGN KEY (raza) REFERENCES RAZAS(nombreR);

-- COMBINACIONES -> RAZAS Y CLASES
ALTER TABLE COMBINACIONES ADD CONSTRAINT FK_COMB_RAZA FOREIGN KEY (raza) REFERENCES RAZAS(nombreR);
ALTER TABLE COMBINACIONES ADD CONSTRAINT FK_COMB_CLASE FOREIGN KEY (clase) REFERENCES CLASES(nombreC);

-- HECHIZOS -> ICONOS
ALTER TABLE HECHIZOS ADD CONSTRAINT FK_HECH_ICONO FOREIGN KEY (icono) REFERENCES ICONOS(idIcono);

-- MACROS -> ICONOS Y HECHIZOS
ALTER TABLE MACROS ADD CONSTRAINT FK_MACRO_ICONO FOREIGN KEY (idIcono) REFERENCES ICONOS(idIcono);
ALTER TABLE MACROS ADD CONSTRAINT FK_MACRO_HECH FOREIGN KEY (idHechizo) REFERENCES HECHIZOS(idHechizo);

-- NPCS -> CIUDADES 
ALTER TABLE NPCS ADD CONSTRAINT FK_NPC_CIUDAD FOREIGN KEY (cuidad) REFERENCES CIUDADES(nombreCiudad);

-- MISIONES -> NPCS
ALTER TABLE MISIONES ADD CONSTRAINT FK_MIS_NPC FOREIGN KEY (npcAsignador) REFERENCES NPCS(nombre);

-- MOBS -> CIUDADES
ALTER TABLE MOBS ADD CONSTRAINT FK_MOB_CIUDAD FOREIGN KEY (ciudad) REFERENCES CIUDADES(nombreCiudad);

-- PERSONAJES -> CLASES
ALTER TABLE PERSONAJES ADD CONSTRAINT FK_PJ_CLASE FOREIGN KEY (clase) REFERENCES CLASES(nombreC);

-- PERSONAJES -> RAZAS
ALTER TABLE PERSONAJES ADD CONSTRAINT FK_PJ_RAZA FOREIGN KEY (raza) REFERENCES RAZAS(nombreR);

-- PERSONAJES -> PROFESIONES (profesion1 y profesion2)
ALTER TABLE PERSONAJES ADD CONSTRAINT FK_PJ_PROF1 FOREIGN KEY (profesion1) REFERENCES PROFESIONES(nombreProfesion);
ALTER TABLE PERSONAJES ADD CONSTRAINT FK_PJ_PROF2 FOREIGN KEY (profesion2) REFERENCES PROFESIONES(nombreProfesion);

-- PERSONAJES -> HERMANDADES
ALTER TABLE PERSONAJES ADD CONSTRAINT FK_PJ_HERMANDAD FOREIGN KEY (hermandad) REFERENCES HERMANDADES(nombreHermandad);

-- PERSONAJES -> CIUDADES
ALTER TABLE PERSONAJES ADD CONSTRAINT FK_PJ_HOGAR  FOREIGN KEY (hogar)    REFERENCES CIUDADES(nombreCiudad);
ALTER TABLE PERSONAJES ADD CONSTRAINT FK_PJ_CIUDAD FOREIGN KEY (ciudad)  REFERENCES CIUDADES(nombreCiudad);

-- PERSONAJES -> MISIONES
ALTER TABLE PERSONAJES ADD CONSTRAINT FK_PJ_MISION FOREIGN KEY (nombreMision) REFERENCES MISIONES(nombreMision);

-- HERMANDADES -> PERSONAJES
ALTER TABLE HERMANDADES ADD CONSTRAINT FK_HERM_LIDER FOREIGN KEY (idLider) REFERENCES PERSONAJES(idPersonaje);

-- PJ_ESTADISTICAS -> PERSONAJES 
ALTER TABLE PJ_ESTADISTICAS ADD CONSTRAINT FK_PJEST_PJ FOREIGN KEY (nombrePJ) REFERENCES PERSONAJES(nombre);

-- PJ_MONTURAS -> PERSONAJES y MONTURAS
ALTER TABLE PJ_MONTURAS ADD CONSTRAINT FK_PJMONT_PJ FOREIGN KEY (nombrePJ) REFERENCES PERSONAJES(nombre);
ALTER TABLE PJ_MONTURAS ADD CONSTRAINT FK_PJMONT_MONT FOREIGN KEY (nombreMontura) REFERENCES MONTURAS(nombreMontura);
ALTER TABLE PJ_MONTURAS ADD CONSTRAINT FK_PJMONT_TRASFIG FOREIGN KEY (trasfiguracion) REFERENCES TRASFIGURACIONES(apariencia);

-- PJ_MASCOTAS -> PERSONAJES y MASCOTAS
ALTER TABLE PJ_MASCOTAS ADD CONSTRAINT FK_PJMASC_PJ FOREIGN KEY (nombrePJ) REFERENCES PERSONAJES(nombre);
ALTER TABLE PJ_MASCOTAS ADD CONSTRAINT FK_PJMASC_MASC FOREIGN KEY (nombreMascota) REFERENCES MASCOTAS(nombreMascota);
ALTER TABLE PJ_MASCOTAS ADD CONSTRAINT FK_PJMASC_TRASFIG FOREIGN KEY (trasfiguracion) REFERENCES TRASFIGURACIONES(apariencia);

-- PJ_JUGUETES -> PERSONAJES y JUGUETES
ALTER TABLE PJ_JUGUETES ADD CONSTRAINT FK_PJJUG_PJ FOREIGN KEY (nombrePJ) REFERENCES PERSONAJES(nombre);
ALTER TABLE PJ_JUGUETES ADD CONSTRAINT FK_PJJUG_JUG FOREIGN KEY (nombreJuguete) REFERENCES JUGUETES(nombreJuguete);
ALTER TABLE PJ_JUGUETES ADD CONSTRAINT FK_PJJUG_TRASFIG FOREIGN KEY (trasfiguracion) REFERENCES TRASFIGURACIONES(apariencia);

-- PJ_ARMAS -> PERSONAJES y ARMAS
ALTER TABLE PJ_ARMAS ADD CONSTRAINT FK_PJARMA_PJ FOREIGN KEY (nombrePJ) REFERENCES PERSONAJES(nombre);
ALTER TABLE PJ_ARMAS ADD CONSTRAINT FK_PJARMA_ARMA FOREIGN KEY (nombreArma) REFERENCES ARMAS(nombreArma);
ALTER TABLE PJ_ARMAS ADD CONSTRAINT FK_PJARMA_TRASFIG FOREIGN KEY (trasfiguracion) REFERENCES TRASFIGURACIONES(apariencia);

-- PJ_ROPAS -> PERSONAJES y ROPAS
ALTER TABLE PJ_ROPAS ADD CONSTRAINT FK_PJROPA_PJ FOREIGN KEY (nombrePJ) REFERENCES PERSONAJES(nombre);
ALTER TABLE PJ_ROPAS ADD CONSTRAINT FK_PJROPA_ROPA FOREIGN KEY (nombreRopa) REFERENCES ROPAS(nombreRopa);
ALTER TABLE PJ_ROPAS ADD CONSTRAINT FK_PJROPA_TRASFIG FOREIGN KEY (trasfiguracion) REFERENCES TRASFIGURACIONES(apariencia);

-- PJ_MOBS -> PERSONAJES y MOBS
ALTER TABLE PJ_MOBS ADD CONSTRAINT FK_PJMOBS_PJ FOREIGN KEY (nombrePJ) REFERENCES PERSONAJES(nombre);
ALTER TABLE PJ_MOBS ADD CONSTRAINT FK_PJMOBS_MOB FOREIGN KEY (mob) REFERENCES MOBS(nombreMob);

-- PJ_BOSSES -> PERSONAJES y MOBS
ALTER TABLE PJ_BOSSES ADD CONSTRAINT FK_PJBOSS_PJ FOREIGN KEY (nombrePJ) REFERENCES PERSONAJES(nombre);
ALTER TABLE PJ_BOSSES ADD CONSTRAINT FK_PJBOSS_MOB FOREIGN KEY (mob) REFERENCES MOBS(nombreMob);

-- PJ_MISIONES -> PERSONAJES y MISIONES
ALTER TABLE PJ_MISIONES ADD CONSTRAINT FK_PJMIS_PJ FOREIGN KEY (nombrePJ) REFERENCES PERSONAJES(nombre);
ALTER TABLE PJ_MISIONES ADD CONSTRAINT FK_PJMIS_MIS FOREIGN KEY (mision) REFERENCES MISIONES(nombreMision);

-- PJ_VENTAS -> PERSONAJES
ALTER TABLE PJ_VENTAS ADD CONSTRAINT FK_PJVEN_PJ FOREIGN KEY (nombrePJ) REFERENCES PERSONAJES(nombre);
ALTER TABLE PJ_VENTAS ADD CONSTRAINT FK_PJVEN_COMP FOREIGN KEY (comprador) REFERENCES PERSONAJES(nombre);

-- PJ_COMPRAS -> PERSONAJES
ALTER TABLE PJ_COMPRAS ADD CONSTRAINT FK_PJCOM_PJ FOREIGN KEY (nombrePJ) REFERENCES PERSONAJES(nombre);
ALTER TABLE PJ_COMPRAS ADD CONSTRAINT FK_PJCOM_VEN FOREIGN KEY (vendedor) REFERENCES PERSONAJES(nombre);

-- ESPECIALIZACIONES -> PERSONAJES
ALTER TABLE ESPECIALIZACIONES ADD CONSTRAINT FK_ESPEC_PJ FOREIGN KEY (idPersonaje) REFERENCES PERSONAJES(idPersonaje);
ALTER TABLE ESPECIALIZACIONES ADD CONSTRAINT FK_ESPEC_HECH FOREIGN KEY (idHechizo) REFERENCES HECHIZOS(idHechizo);

-- RANKINGPERSONAJES -> PERSONAJES
ALTER TABLE RANKINGPERSONAJES ADD CONSTRAINT FK_RANKPJ_PJ FOREIGN KEY (idPersonaje) REFERENCES PERSONAJES(nombre);

-- RANKINGHERMANDADES -> HERMANDADES
ALTER TABLE RANKINGHERMANDADES ADD CONSTRAINT FK_RANKHERM_HERM FOREIGN KEY (idHermandad) REFERENCES HERMANDADES(idHermandad);

-- CADAOBJETO -> OBJETOS
ALTER TABLE MONTURAS ADD CONSTRAINT FK_MONT_OBJ FOREIGN KEY (nombreMontura) REFERENCES OBJETOS (nombreObjeto);

ALTER TABLE MASCOTAS ADD CONSTRAINT FK_MASC_OBJ FOREIGN KEY (nombreMascota) REFERENCES OBJETOS (nombreObjeto);

ALTER TABLE JUGUETES ADD CONSTRAINT FK_JUG_OBJ FOREIGN KEY (nombreJuguete) REFERENCES OBJETOS (nombreObjeto);

ALTER TABLE ARMAS ADD CONSTRAINT FK_ARMA_OBJ FOREIGN KEY (nombreArma) REFERENCES OBJETOS (nombreObjeto);

ALTER TABLE ROPAS ADD CONSTRAINT FK_ROPA_OBJ FOREIGN KEY (nombreRopa) REFERENCES OBJETOS (nombreObjeto);

-- RECOMPENSAS -> MISIONES Y OBJETOS
ALTER TABLE RECOMPENSAS ADD CONSTRAINT FK_RECOMP_MISION FOREIGN KEY (idMision) REFERENCES MISIONES (idMision);
ALTER TABLE RECOMPENSAS ADD CONSTRAINT FK_RECOMP_OBJ FOREIGN KEY (idObjeto) REFERENCES OBJETOS (idObjeto);