/*
XDisparadores

Eliminación de disparadores
*/

DROP TRIGGER TRG_PJ_ID_AUTOINC;
DROP TRIGGER TRG_PJ_NOMBRE_VALIDO;
DROP TRIGGER TRG_IDMISION_AUTOINC;
DROP TRIGGER TRG_IDMOB_AUTOINC;
DROP TRIGGER TRG_IDTRASFIG_AUTOINC;
DROP TRIGGER TRG_PJ_RAZA_CLASE;
DROP TRIGGER TRG_PJ_SALUD_AUTO;
DROP TRIGGER TRG_PJ_ESTADO_AUTO;
DROP TRIGGER TRG_ACTUALIZAR_EXP_MOB;
DROP TRIGGER TRG_ACTUALIZAR_ORO_MOB;
DROP TRIGGER TRG_ACTUALIZAR_EXP_BOSS;
DROP TRIGGER TRG_ACTUALIZAR_MISION_COMPLETADA;
DROP TRIGGER TRG_ACTUALIZAR_ORO_VENTA;
DROP TRIGGER TRG_ACTUALIZAR_ORO_COMPRA;
DROP TRIGGER TRG_ACTUALIZAR_STATS_PJ;
DROP TRIGGER TRG_PJ_HERMANDAD_LIMITE;
DROP TRIGGER TRG_MOB_NIVEL_CIUDAD;
DROP TRIGGER TRG_ROPA_ESTADISTICAS;
DROP TRIGGER TRG_RANKING_PJ;
DROP TRIGGER TRG_PVB_VICTORIA;