/*
Acciones

Definición de las acciones de referencia
*/


-- PJ_ESTADISTICAS -> PERSONAJES  (usamos CASCADE)
ALTER TABLE PJ_ESTADISTICAS DROP CONSTRAINT FK_PJEST_PJ;
ALTER TABLE PJ_ESTADISTICAS ADD CONSTRAINT FK_PJEST_PJ FOREIGN KEY (nombrePJ) REFERENCES PERSONAJES(nombre) ON DELETE CASCADE;

-- PJ_MONTURAS -> PERSONAJES  (usamos CASCADE)
ALTER TABLE PJ_MONTURAS DROP CONSTRAINT FK_PJMONT_PJ;
ALTER TABLE PJ_MONTURAS ADD CONSTRAINT FK_PJMONT_PJ FOREIGN KEY (nombrePJ) REFERENCES PERSONAJES(nombre) ON DELETE CASCADE;

-- PJ_MASCOTAS -> PERSONAJES  (usamos CASCADE)
ALTER TABLE PJ_MASCOTAS DROP CONSTRAINT FK_PJMASC_PJ;
ALTER TABLE PJ_MASCOTAS ADD CONSTRAINT FK_PJMASC_PJ FOREIGN KEY (nombrePJ) REFERENCES PERSONAJES(nombre) ON DELETE CASCADE;

-- PJ_JUGUETES -> PERSONAJES  (usamos CASCADE)
ALTER TABLE PJ_JUGUETES DROP CONSTRAINT FK_PJJUG_PJ;
ALTER TABLE PJ_JUGUETES ADD CONSTRAINT FK_PJJUG_PJ FOREIGN KEY (nombrePJ) REFERENCES PERSONAJES(nombre) ON DELETE CASCADE;

-- PJ_ARMAS -> PERSONAJES  (usamos CASCADE)
ALTER TABLE PJ_ARMAS DROP CONSTRAINT FK_PJARMA_PJ;
ALTER TABLE PJ_ARMAS ADD CONSTRAINT FK_PJARMA_PJ FOREIGN KEY (nombrePJ) REFERENCES PERSONAJES(nombre) ON DELETE CASCADE;

-- PJ_ROPAS -> PERSONAJES  (usamos CASCADE)
ALTER TABLE PJ_ROPAS DROP CONSTRAINT FK_PJROPA_PJ;
ALTER TABLE PJ_ROPAS ADD CONSTRAINT FK_PJROPA_PJ FOREIGN KEY (nombrePJ) REFERENCES PERSONAJES(nombre) ON DELETE CASCADE;

-- PJ_MOBS -> PERSONAJES  (usamos CASCADE)
ALTER TABLE PJ_MOBS DROP CONSTRAINT FK_PJMOBS_PJ;
ALTER TABLE PJ_MOBS ADD CONSTRAINT FK_PJMOBS_PJ FOREIGN KEY (nombrePJ) REFERENCES PERSONAJES(nombre) ON DELETE CASCADE;

-- PJ_BOSSES -> PERSONAJES  (usamos CASCADE)
ALTER TABLE PJ_BOSSES DROP CONSTRAINT FK_PJBOSS_PJ;
ALTER TABLE PJ_BOSSES ADD CONSTRAINT FK_PJBOSS_PJ FOREIGN KEY (nombrePJ) REFERENCES PERSONAJES(nombre) ON DELETE CASCADE;

-- PJ_MISIONES -> PERSONAJES  (usamos CASCADE)
ALTER TABLE PJ_MISIONES DROP CONSTRAINT FK_PJMIS_PJ;
ALTER TABLE PJ_MISIONES ADD CONSTRAINT FK_PJMIS_PJ FOREIGN KEY (nombrePJ) REFERENCES PERSONAJES(nombre) ON DELETE CASCADE;

-- PJ_VENTAS -> PERSONAJES  (usamos CASCADE)
ALTER TABLE PJ_VENTAS DROP CONSTRAINT FK_PJVEN_PJ;
ALTER TABLE PJ_VENTAS ADD CONSTRAINT FK_PJVEN_PJ FOREIGN KEY (nombrePJ) REFERENCES PERSONAJES(nombre) ON DELETE CASCADE;
-- comprador usamos SET NULL si el comprador se elimina
ALTER TABLE PJ_VENTAS DROP CONSTRAINT FK_PJVEN_COMP;
ALTER TABLE PJ_VENTAS ADD CONSTRAINT FK_PJVEN_COMP FOREIGN KEY (comprador) REFERENCES PERSONAJES(nombre) ON DELETE SET NULL;

-- PJ_COMPRAS -> PERSONAJES  (usamos CASCADE)
ALTER TABLE PJ_COMPRAS DROP CONSTRAINT FK_PJCOM_PJ;
ALTER TABLE PJ_COMPRAS ADD CONSTRAINT FK_PJCOM_PJ FOREIGN KEY (nombrePJ) REFERENCES PERSONAJES(nombre) ON DELETE CASCADE;

-- ESPECIALIZACIONES -> PERSONAJES  (usamos CASCADE)
ALTER TABLE ESPECIALIZACIONES DROP CONSTRAINT FK_ESPEC_PJ;
ALTER TABLE ESPECIALIZACIONES ADD CONSTRAINT FK_ESPEC_PJ FOREIGN KEY (idPersonaje) REFERENCES PERSONAJES(id) ON DELETE CASCADE;

-- RANKINGPERSONAJES -> PERSONAJES  (usamos CASCADE)
ALTER TABLE RANKINGPERSONAJES DROP CONSTRAINT FK_RANKPJ_PJ;
ALTER TABLE RANKINGPERSONAJES ADD CONSTRAINT FK_RANKPJ_PJ FOREIGN KEY (idPersonaje) REFERENCES PERSONAJES(nombre) ON DELETE CASCADE;

-- PERSONAJES -> HERMANDADES  (usamos SET NULL al borrar hermandad)
ALTER TABLE PERSONAJES DROP CONSTRAINT FK_PJ_HERMANDAD;
ALTER TABLE PERSONAJES ADD CONSTRAINT FK_PJ_HERMANDAD FOREIGN KEY (hermandad) REFERENCES HERMANDADES(nombreHermandad) ON DELETE SET NULL;

-- PERSONAJES -> MISIONES (usamos SET NULL al borrar mision)
ALTER TABLE PERSONAJES DROP CONSTRAINT FK_PJ_MISION;
ALTER TABLE PERSONAJES ADD CONSTRAINT FK_PJ_MISION FOREIGN KEY (nombreMision) REFERENCES MISIONES(nombreMision) ON DELETE SET NULL;

-- PERSONAJES -> PROFESIONES  (usamos SET NULL)
ALTER TABLE PERSONAJES DROP CONSTRAINT FK_PJ_PROF1;
ALTER TABLE PERSONAJES ADD CONSTRAINT FK_PJ_PROF1 FOREIGN KEY (profesion1) REFERENCES PROFESIONES(nombreProfesion) ON DELETE SET NULL;
ALTER TABLE PERSONAJES DROP CONSTRAINT FK_PJ_PROF2;
ALTER TABLE PERSONAJES ADD CONSTRAINT FK_PJ_PROF2 FOREIGN KEY (profesion2) REFERENCES PROFESIONES(nombreProfesion) ON DELETE SET NULL;

-- HERMANDADES -> PERSONAJES lider  (usamos SET NULL al borrar PJ lider)
ALTER TABLE HERMANDADES DROP CONSTRAINT FK_HERM_LIDER;
ALTER TABLE HERMANDADES ADD CONSTRAINT FK_HERM_LIDER FOREIGN KEY (idLider) REFERENCES PERSONAJES(nombre) ON DELETE SET NULL;

-- BONIFICACIONESRACIALES -> RAZAS  (usamos CASCADE)
ALTER TABLE BONIFICACIONESRACIALES DROP CONSTRAINT FK_BONIF_RAZA;
ALTER TABLE BONIFICACIONESRACIALES ADD CONSTRAINT FK_BONIF_RAZA FOREIGN KEY (raza) REFERENCES RAZAS(nombreR) ON DELETE CASCADE;

-- COMBINACIONES -> RAZAS  (usamos CASCADE)
ALTER TABLE COMBINACIONES DROP CONSTRAINT FK_COMB_RAZA;
ALTER TABLE COMBINACIONES ADD CONSTRAINT FK_COMB_RAZA FOREIGN KEY (raza) REFERENCES RAZAS(nombreR) ON DELETE CASCADE;

-- COMBINACIONES -> CLASES  (usamos CASCADE)
ALTER TABLE COMBINACIONES DROP CONSTRAINT FK_COMB_CLASE;
ALTER TABLE COMBINACIONES ADD CONSTRAINT FK_COMB_CLASE FOREIGN KEY (clase) REFERENCES CLASES(nombreC) ON DELETE CASCADE;

-- RANKINGHERMANDADES -> HERMANDADES  (usamos CASCADE)
ALTER TABLE RANKINGHERMANDADES DROP CONSTRAINT FK_RANKHERM_HERM;
ALTER TABLE RANKINGHERMANDADES ADD CONSTRAINT FK_RANKHERM_HERM FOREIGN KEY (idHermandad) REFERENCES HERMANDADES(idHermandad) ON DELETE CASCADE;

-- MISIONES -> NPCS  (usamos SET NULL si el NPC se borra)
ALTER TABLE MISIONES DROP CONSTRAINT FK_MIS_NPC;
ALTER TABLE MISIONES ADD CONSTRAINT FK_MIS_NPC FOREIGN KEY (npcAsignador) REFERENCES NPCS(nombre) ON DELETE SET NULL;

-- HECHIZOS -> ICONOS  (usamos SET NULL)
ALTER TABLE HECHIZOS DROP CONSTRAINT FK_HECH_ICONO;
ALTER TABLE HECHIZOS ADD CONSTRAINT FK_HECH_ICONO FOREIGN KEY (icono) REFERENCES ICONOS(idIcono) ON DELETE SET NULL;

-- MACROS -> ICONOS  (usamos SET NULL)
ALTER TABLE MACROS DROP CONSTRAINT FK_MACRO_ICONO;
ALTER TABLE MACROS ADD CONSTRAINT FK_MACRO_ICONO FOREIGN KEY (idIcono) REFERENCES ICONOS(idIcono) ON DELETE SET NULL;

-- MACROS -> HECHIZOS  (usamos SET NULL)
ALTER TABLE MACROS DROP CONSTRAINT FK_MACRO_HECH;
ALTER TABLE MACROS ADD CONSTRAINT FK_MACRO_HECH FOREIGN KEY (idHechizo) REFERENCES HECHIZOS(idHechizo) ON DELETE SET NULL;