/*
XTablas
Eliminación de tablas
*/
DROP TABLE RANKINGHERMANDADES;
DROP TABLE RANKINGPERSONAJES;
DROP TABLE ESPECIALIZACIONES;
DROP TABLE PJ_COMPRAS;
DROP TABLE PJ_VENTAS;
DROP TABLE PJ_MISIONES;
DROP TABLE PJ_BOSSES;
DROP TABLE PJ_MOBS;
DROP TABLE PJ_ROPAS;
DROP TABLE PJ_ARMAS;
DROP TABLE PJ_JUGUETES;
DROP TABLE PJ_MASCOTAS;
DROP TABLE PJ_MONTURAS;
DROP TABLE PJ_ESTADISTICAS;
DROP TABLE PERSONAJES;
DROP TABLE HERMANDADES;
DROP TABLE PVBS;
DROP TABLE RECOMPENSAS;
DROP TABLE MISIONES;
DROP TABLE MOBS;
DROP TABLE NPCS;
DROP TABLE COMBINACIONES;
DROP TABLE BONIFICACIONESRACIALES;
DROP TABLE RAZAS;
DROP TABLE CLASES;
DROP TABLE TRASFIGURACIONES;
DROP TABLE ROPAS;
DROP TABLE ARMAS;
DROP TABLE JUGUETES;
DROP TABLE MASCOTAS;
DROP TABLE MONTURAS;
DROP TABLE MACROS;
DROP TABLE HECHIZOS;
DROP TABLE ICONOS;
DROP TABLE PROFESIONES;
DROP TABLE LOGROS;
DROP TABLE CIUDADES;
DROP TABLE PAISES;
DROP TABLE CONTINENTES;
DROP TABLE MUNDOS;
DROP TABLE OBJETOS;

-- Secuencias
DROP SEQUENCE SEQ_PJ_ID;
DROP SEQUENCE SEQ_IDMISION;
DROP SEQUENCE SEQ_IDMOB;
DROP SEQUENCE SEQ_IDTRASFIG;
DROP SEQUENCE SEQ_IDHERMANDAD;
DROP SEQUENCE SEQ_IDPVB;
DROP SEQUENCE SEQ_IDICONO;
DROP SEQUENCE SEQ_IDHECHIZO;
DROP SEQUENCE SEQ_IDMACRO;
DROP SEQUENCE SEQ_IDOBJETO;